exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    - id: autoflake
      args:
      - "--in-place"
      - "--recursive"
      - "--expand-star-imports"
      - "--remove-duplicate-keys"
      - "--remove-all-unused-imports"
      - "--remove-unused-variables"
      - "--quiet"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length=120"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args:
      - "--profile"
      - "black"
      - "--filter-files"
