exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/bwhmather/ssort
    rev: v0.11.6
    hooks:
    - id: ssort

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    - id: autoflake
      args:
      - "--in-place"
      - "--recursive"
      - "--expand-star-imports"
      - "--remove-duplicate-keys"
      - "--remove-all-unused-imports"
      - "--remove-unused-variables"
      - "--quiet"

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
        - "--in-place"
        - "--black"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length=120"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args:
      - "--profile"
      - "black"
      - "--filter-files"
